/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const fbConfig = {
  apiKey: "AIzaSyAisJm8E5IetbmUh5tDcpwZI_Ph64BGSEk",
  authDomain: "react-board-bb9f0.firebaseapp.com",
  databaseURL: "https://react-board-bb9f0.firebaseio.com",
  projectId: "react-board-bb9f0",
  storageBucket: "react-board-bb9f0.appspot.com",
  messagingSenderId: "567595814045"
}
