/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const fbConfig = {
  apiKey: "AIzaSyAa96j9Rvrjqft2ewwLXXonq7yF9cpWIgQ",
  authDomain: "react-fileupload.firebaseapp.com",
  databaseURL: "https://react-fileupload.firebaseio.com",
  projectId: "react-fileupload",
  storageBucket: "react-fileupload.appspot.com",
  messagingSenderId: "543727054805"
}
